### ISSUE TITLE
Plugin is incompatible and requires its author to update

### ISSUE THREAD

**Issue by Puzzle-Drops** [dave-kramer/discord-screenshot#1]
![image](https://github.com/dave-kramer/discord-screenshot/assets/86485071/966ecd53-79ba-4fb5-9e6f-9409c831cd8e)

**Comment by dave-kramer** [comment]
Ah didn't notice there were plugin changes to runelite. however I updated it and works again, just have to wait for runelite to review the pull request and it'll be available again.
