### ISSUE TITLE
Ability to auto screenshot?

### ISSUE THREAD

**Issue by connr** [dave-kramer/discord-screenshot#2]
Have you tried or thought about this being able to send screenshots automatically to the hook? Essentially the same as the original screenshot plug with pets, deaths, kills?

**Comment by dave-kramer** [comment]
Sorry for the late reply. I'm not sure what you're asking, You mean randomly screenshotting and sending it to the webhook?

**Comment by connr** [comment]
No worries.

Not randomly no. You know how the official screenshot plugin saves to the directory on deaths, pets, kills, levels etc? Essentially wondering if it would be possible to have those screenshots send without having to click the button

**Comment by dave-kramer** [comment]
Ah, I could implement that, however there are multiple plugins available that already do exactly that.
